package fr.votreprojet.util;

public enum TypeEvenement {

    //Annonces
    NOUVELLE_ANNONCE,
    ANNONCE_MODIFIEE,
    ANNONCE_SUPPRIMEE,
    ANNONCE_SIGNALEE,
    ANNONCE_RESERVEE,
    ANNONCE_TERMINEE,

    // Messages
    NOUVEAU_MESSAGE,
    MESSAGE_LU,
    MESSAGE_SUPPRIME,
    MESSAGE_SIGNALE,

    // Evènements
    EVENEMENT_CREE,
    EVENEMENT_MODIFIE,
    EVENEMENT_ANNULE,
    EVENEMENT_INSCRIT,
    EVENEMENT_DESINSCRIT,

    // Signalements
    SIGNALEMENT_CREE,
    SIGNALEMENT_TRAITE,
    SIGNALEMENT_RESOLU,
    SIGNALEMENT_ESCALADE,

    // Évaluations
    EVALUATION_AJOUTEE,
    EVALUATION_MODIFIEE,
    EVALUATION_SUPPRIMEE,
    EVALUATION_SIGNALEE,

    // Utilisateurs
    UTILISATEUR_INSCRIT,
    UTILISATEUR_MODIFIE,
    UTILISATEUR_VALIDE,
    UTILISATEUR_SUSPENDU,

    // Tontines
    TONTINE_CREE,
    TONTINE_MODIFIEE,
    TONTINE_SUPPRIMEE,
    TONTINE_NOUVEAU_PARTICIPANT,   
    TONTINE_PAIEMENT_EFFECTUE,      
    TONTINE_TOUR_DISTRIBUE,  

}
